vich_uploader:
    db_driver: orm

    mappings:
        snakes_image:
            uri_prefix: '%app.path.snakes_image%'
            upload_destination: '%kernel.project_dir%/public%app.path.snakes_image%'

        distribution_image:
            uri_prefix: '%app.path.distribution_image%'    
            upload_destination: '%kernel.project_dir%/public%app.path.distribution_image%'

        lezards_image:
            uri_prefix: '%app.path.lezards_image%'
            upload_destination: '%kernel.project_dir%/public%app.path.lezards_image%'